export const ScheduleData = [
    {
        date: "2023-11-06",
        labelColor: "#eb2f96",
        title: "12345678901234567890",
        isDayAll: 0,
        id: 1,
        attendee: [
            { id: 1, name: "한유정" },
            { id: 2, name: "우주영" },
        ],
        location: "기본위치",
        cycle: 3,
        repeatType: "date",
        repeatCount: "",
        repeatEndDate: "2023-11-15",
        description: "",
    },
    {
        date: "2023-11-07",
        labelColor: "#f6bf26",
        title: "12345678901234567890",
        isDayAll: 1,
        id: 2,
        attendee: [
            { id: 1, name: "한유정" },
            { id: 2, name: "우주영" },
        ],
        location: "기본위치",
        cycle: 3,
        repeatType: "date",
        repeatCount: "",
        repeatEndDate: "2023-11-15",
        description: "",
    },
    {
        date: "2023-11-08",
        labelColor: "#f5222d",
        title: "123123",
        isDayAll: 0,
        id: 3,
        attendee: [
            { id: 1, name: "한유정" },
            { id: 2, name: "우주영" },
        ],
        location: "기본위치",
        cycle: 3,
        repeatType: "date",
        repeatCount: "",
        repeatEndDate: "2023-11-15",
        description: "",
    },
    {
        date: "2023-11-09",
        labelColor: "#94da72",
        title: "456",
        isDayAll: 1,
        id: 5,
        attendee: [
            { id: 1, name: "한유정" },
            { id: 2, name: "우주영" },
        ],
        location: "기본위치",
        cycle: 3,
        repeatType: "date",
        repeatCount: "",
        repeatEndDate: "2023-11-15",
        description: "",
    },
];
